language: python
python:
  - 2.7

services:
  - mongodb
  - redis-server

env:
  - TOX_ENV=py27

install:
  - pip install flake8
  - pip install coveralls
  - pip install tox

script:
  - flake8 .
  - tox -e $TOX_ENV

after_success:
  - coveralls
